<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use DB;

class AddonTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    
            // ['1','Rear Camera']
    public function run(): void
    {
        $addons = [
    ['1','10.1 Inch - Android Rear Entertainment (All Brands/Models)'],
	['2','11.5 Inch - Android Rear Entertainment (All Brands/Models)'],
	['3','13.3 Inch - Android Rear Entertainment'],
	['4','13A Plug Volex'],
	['5','18 Size Legender Rims With Exchange 4 Pieces Only'],
	['6','2 Tone Paint'],
	['7','3 Core Wire 2.5mm Cable Roll'],
	['8','360 Camera'],
	['9','360 Camera 2D'],
	['10','360 Camera 3D'],
	['11','360 Camera HD'],
	['12','360 Camera Special LC300'],
	['13','360 Camera Universal Camera'],
	['14','3M Tinting (Sedan/Hatch Back)'],
	['15','3M Tinting (SUV)'],
	['16','4 Rims And 4 Tyres With Exchange Of Tyres'],
	['17','5 Rims And 5 Tyres From 17 To 18, Only Tyres Exchanged'],
	['18','5 Rims And 5 Tyres From 17 To 18, With Exchange Of Tyres And Rims'],
	['19','5 Rims And 5 Tyres From 17 To 19, Only Tyres Exchanged'],
	['20','5 Rims And 5 Tyres From 17 To 19, With Exchange Of Tyres And Rims'],
	['21','5 Rims And 5 Tyres From 18 To 20 Only Tyres Exchanged'],
	['22','5 Rims And 5 Tyres From 18 To 20 With Exchange Of Tyres And Rims'],
	['23','5 Rims And 5Tyres With Exchange Of Tyres 17 And 18 Size'],
	['24','70th Anniversary Badge'],
	['25','9" Inch - Android Rear Entertainment (All Brands/Models)'],
	['26','9" Inch - Featured Rear Entertainment (All Brands/Models)'],
	['27','AC Filter'],
	['28','Adventure Body Kit'],
	['29','Adventure Logo'],
	['30','Airport Vehicle Design Paint'],
	['31','Alloy Rims 4 Pieces'],
	['32','Alloy Rims 4 Pieces With Excahnge Of Alloy Rims'],
	['33','Alloy Rims 5 Pieces'],
	['34','Alloy Rims 5 Pieces 17 Size Without Alloy Rims Exchange'],
	['35','Alloy Rims 5 Pieces Without Exchange'],
	['36','Alloy Rims 5 Pieces Without Exchange 20 Inch'],
	['37','Ambience Dash Board Light + Doors'],
	['38','Ambulance With Sandwich Panel'],
	['39','Android DVD With Camera'],
	['40','Android Rear Entertainment (12 Inch)'],
	['41','Automatic Respirator For Ambulance'],
	['42','B6-Armoring'],
	['43','Back Light Chrome LED With Red Light'],
	['44','Bash Plate/ Skid Plate'],
	['45','Basic Ambulance'],
	['46','Basic Ambulance With Extended Fiber Glass Roof And Partition'],
	['47','Basic Ambulance With Wash Basin And 50-75 Litre Water Tank With Tap On The Underside'],
	['48',"Basic Ambulance'S Wash Basin Water Tank (50 Litres) And Posett"],
	['49','Basic Warranty For Gear And Engine'],
	['50','Basic Warranty For Gear And Engine (Without Claim)'],
	['51','Beacon Light'],
	['52','Bedliner'],
	['53','Belt Sticker Change'],
	['54','Black Edition Without Rims Paints'],
	['55','Blue Light Interior Down Side'],
	['56','Body Kit 2022 With Head Lights'],
	['57','Body Kit Fixing And Paint Charges Only'],
	['58','Body Kit Prado Fj150'],
	['59','Body Kit With Lexus Design 2022'],
	['60','Body Sticker'],
	['61','Body Sticker (All Brands/Models)'],
	['62','Bonnet Chrome Protector'],
	['63','Both Right Side Doors Painting'],
	['64','Brabus G800 Exterior Conversion With Rim And Tyre'],
	['65','Bsd Radar'],
	['66','Bullbar'],
	['67','Bullbar (Pickups & SUVs)'],
	['68','Bumper Complete (Both Fenders, Grill, Steel Bumper, Chrome Nickel, Bonnet Chrome, Inner Fender, Bumper Bracket)'],
	['69','Bumper Protector'],
	['70','Camping Edition'],
	['71','Canopy'],
	['72','Carry Body Canopy'],
	['73','Carryboy'],
	['74','Carryboy + Paint + Fixing'],
	['75','Ceramic Tinting'],
	['76','Ceramic Tinting (Sedan/Hatch Back)'],
	['77','Ceramic Tinting (SUV)'],
	['78','Chamois Fabric Seats'],
	['79','Chasis Sticker Change'],
	['80','Chrome Decoration'],
	['81','Chrome Door Handles'],
	['82','Chrome Front Grill'],
	['83','Chrome Window Moulding Cover (Original)'],
	['84','Complete Exhaust System'],
	['85','Customized Leather Napa Seats'],
	['86','Dashboard Paint'],
	['87','Digital Rear Camera'],
	['88','Digital Speedo Meter'],
	['89','Door Handle Chrome Cover'],
	['90','Door Sil 4 Sides'],
	['91','Door Sill Scuff Per Door (Not Like Original) Per Door'],
	['92','Down Spoilers Front And Back Modelilista (No Chrome Edition)'],
	['93','DVD With Camera'],
	['94','Electric Fuel Pump'],
	['95','Electric Seats (Each Seat)'],
	['96','Electric Seats Each Seat'],
	['97','Electric Suction Door Closer/Automatic Door Closer'],
	['98','Emergency Warning Triangle'],
	['99','Engine Air Filter'],
	['100','Exhaust Mounting With Fixing Charges'],
	['101','Exhaust Tip Inc Welding'],
	['102','Face Lift (Bumper, Grill, Fog Lamp, Fog Lamps Cover, Inner Fender,Bumper Brackets)'],
	['103','Fender Work'],
	['104','Fire Extinguisher 2Kg'],
	['105','First Aid Kit (42 Pieces)'],
	['106','Flag Pole (All Cars)'],
	['107','Flash Lights For Bumer'],
	['108','Floor Mat 3D'],
	['109','Floor Plastic'],
	['110','Fog Lamps'],
	['111','Fog Lamps Chrome Cover'],
	['112','Fog Lamps LED Light'],
	['113','Fog Lamps Yellow Light'],
	['114','Fog Lights (Pickups & SUVs)'],
	['115','Frame Guard'],
	['116','Front And Rear Bumper Chrome Edition With Paint And Fixing'],
	['117','Front Android DVD'],
	['118','Front Bumper Protector'],
	['119','Front DVD'],
	['120','Front DVD Android'],
	['121','Front DVD Big Screen (Android)'],
	['122','Front DVD Big Screen With Apple Car Play'],
	['123','Front DVD Normal Screen (Android)'],
	['124','Front DVD Original Screen'],
	['125','Front DVD Original Type'],
	['126','Front Glass Emblem'],
	['127','Front Grill'],
	['128','Front Lamps Black Out'],
	['129','Front LED Lights (Taiwan)'],
	['130','Front Original Double Volume DVD'],
	['131','Fuel Filter'],
	['132','Full Body Color Change To 4E9 + Coating'],
	['133','Full Body Peelable Paint'],
	['134','Gift Wrapping Bow'],
	['135','Grill Paint'],
	['136','Half Down Recovery Fabrication'],
	['137','Hidup Prado'],
	['138','High Quality Bullbar + Winch'],
	['139','Hilux Rims (Act0 5 Pieces'],
	['140','Hydraulic Jack (1500Kg)'],
	['141','Industrial Plug 16 Amp'],
	['142','Installation Of P338, P335, P334, P333, P332 With Extra Wires, Flexible Pipes And Brackets'],
	['143','Interior Change'],
	['144','Interior(Fibre Carbon)'],
	['145','Jbl Sound System'],
	['146','Jerry Can Carrier'],
	['147','Key Remote (China)'],
	['148','Land Cruiser Logo'],
	['149','LC300 Shadow Light'],
	['150','Leather Seats'],
	['151','Leather Seats (Mixed Leather)'],
	['152','Leather Seats (Napa+Leather) + Dash Board + Gear Console'],
	['153','Leather Seats Normal Holes Desgin'],
	['154','Leather Seats VXL Design'],
	['155','Leather Seats With LC200 Design'],
	['156','Leather Seats With LC300 Design'],
	['157','LED Board'],
	['158','LED Fog Lights'],
	['159','LED Front Grill'],
	['160','LED Front Lights'],
	['161','LED Lights'],
	['162','Legender Complete Kit'],
	['163','Legender Logo'],
	['164','Legender Rims 18 Size (4 Pieces)'],
	['165','Legender Word Imposing On Head Rest'],
	['166','Manual Respirator For Ambulance'],
	['167','Medical Portabel Suction Machine.'],
	['168','Micro Fiber Seats'],
	['169','Micro Fiber Seats With Normal Holes'],
	['170','Mix Leather Seat'],
	['171','Modellista Body Kit With Fenders'],
	['172','Monster Edition Conversion'],
	['173','Moulding Cover Front Right Side'],
	['174','Moulding Cover Rear Right Side'],
	['175','Mud Flap Set Of 4 Pieces'],
	['176','Multi-Flashing Roof Light Bar With Siren & Speaker'],
	['177','Napa Seats'],
	['178','Napa Seats With Center Leather Of Front 2 Seats'],
	['179','Night Package Lights'],
	['180','Normal Tinting (Pick Ups, Sc And Dc)'],
	['181','Normal Tinting (Sedan/Hatch Back)'],
	['182','Normal Tinting (SUV)'],
	['183','Off Road Package That Incliudes[ Bullbar, Off Road Tyres, Roof Rack, Bedliner, Winch, Spot Lights, Body Sticker, Rear Steel Bumper With 2 Tyres Bracket'],
	['184','Oil Filter'],
	['185','Oxygen Cylinder Regulator , Humidifier Flow Meter , Outlet For Ambulance'],
	['186','Parking Sensor'],
	['187','Pillar Exterior Plastic Moulding Front'],
	['188','Pillar Exterior Plastic Moulding Rear Back Side'],
	['189','Pillar Exterior Plastic Moulding Rear Front Side'],
	['190','Pirelli 295/40/22 Tyres And Rims'],
	['191','Plastic Cover Pic'],
	['192','Plastic Flooring (Sedan)'],
	['193','Plastic Flooring (SUV & Pickups)'],
	['194','Plastic Over Fender'],
	['195','Police Car Radio'],
	['196','Police Lights'],
	['197','Power Seats'],
	['198','Power Tail Gate'],
	['199','Prado Body Kit With Grill 2021 And Paint'],
	['200','Prado Interior Change'],
	['201','Prado Lexus Style Body Kit'],
	['202','Prado Lexus Style Grill'],
	['203','Prado Logo Door Light Down Reflection'],
	['204','Premium Leather Seats With Replica Of Bently Fly Spur Seats, Door Panels And Center Console'],
	['205','Push Start Original Type'],
	['206','Push Start Original Type( With Pressing Brake)'],
	['207','Push Start Original Type( Without Pressing Brake)'],
	['208','Push Start With Pressing Brake'],
	['209','Push Start With Pressing Brake ( Without Pressing Brake)'],
	['210','PVC Seats'],
	['211','Ramp Chrome'],
	['212','Rav 4 Adventure Conversion'],
	['213','Rear Badges'],
	['214','Rear Badges VXR Etc'],
	['215','Rear Camera'],
	['216','Rear Camera (All Sedans)'],
	['217','Rear Camera (SUV & Pickups)'],
	['218','Rear Chrome Bumper'],
	['219','Rear Chrome Nickel'],
	['220','Rear Chrome Nickel Fortuner'],
	['221','Rear Chrome Nickel Fortuner With Red Light'],
	['222','Rear Entertainment 11.5 Inch'],
	['223','Rear Entertainment LC300 Type'],
	['224','Rear Entertainment Original Type (Black)'],
	['225','Rear Mirror Camera'],
	['226','Rear Spoiler Light'],
	['227','Rear Spoiler With Light'],
	['228','Rear Steel Bumper'],
	['229','Rear Steel Bumper With Brackets'],
	['230','Rear Sub Bumper + Jerry Can + Spare Tyre Bracket'],
	['231','RHD Front Door'],
	['232','RHD Rear Door'],
	['233','Rims Paints'],
	['234','Roll Bar With Brake Light'],
	['235','Roll Bar With LED Lights'],
	['236','Rollbar'],
	['237','Rollbar (Metal)'],
	['238','Rollbar (Plastic)'],
	['239','Roof Rack'],
	['240','Roof Rack Lexus Style'],
	['241','Roof Rack Original Style'],
	['242','Roof Rail'],
	['243','Roof Wrapping (Black)'],
	['244','Sahara Badge'],
	['245','Seat Heater'],
	['246','Seat Heater Cooler'],
	['247','Seat Heating System'],
	['248','Shutter'],
	['249','Shutter Automatic'],
	['250','Shutter Manual'],
    ['251','Side Fender'],
	['252','Side Mirror Chrome Cover'],
	['253','Side Mirror Chrome Glass Assy'],
	['254','Side Mirror Right Side Cover'],
	['255','Side Mirror With Indicator Light'],
	['256','Side Moulding'],
	['257','Side Moulding With Plastic Cover'],
	['258','Side Step With Protection Iron Bar'],
	['259','Side Steps'],
	['260','Single Volume DVD'],
	['261','Sink With Cabinet For Ambulance'],
	['262','Snorkel'],
	['263','Spare Tire Carrier'],
	['264','Special Front DVD'],
	['265','Spot Lights (Pickups & SUVs)'],
	['266','Stainless Steel Waste Bin'],
	['267','Steering (Fibre Carbon And Alcantara)'],
	['268','Steering Buttons'],
	['269','Sticker Wrapping On Car Body'],
	['270','Stop Light Red'],
	['271','Storage Box'],
	['272','Sun Visor'],
	['273','Tail Door Handle Cover Hilux'],
	['274','Tail Gate Hydraulic'],
	['275','Tesla Screen'],
	['276','Tester'],
	['277','Tonneau Cover Hardtop Material'],
	['278','Tow Bar'],
	['279','Tow Bowl Bar'],
	['280','Tow Hitch Bar With Bracket'],
	['281','Tow Hitch Electric Socket 6 Pin (Pickups & SUVs)'],
	['282','Tw Twin Turbo'],
	['283','Twin Turbo Logo'],
	['284','Tyre 235/55R20'],
	['285','Tyre Down Work (With Exchange Of Old Gate)'],
	['286','Tyre Up Work (Without Exchange Of Old Gate)'],
	['287','Tyres 275/50/22 And Rims With Exchange'],
	['288','Tyres And Alloy Rims 5 Pieces 18 Inch With Exchange Of Wheels And Rims'],
	['289','Univesal Power Windows'],
	['290','Upgrade Front And Back Bumper To Full Option (Withpaint)'],
	['291','VIN Plate'],
	['292','Wheel Cover PVC'],
	['293','Wheel Spanner'],
	['294','Winch (Pickups & SUV)'],
	['295','Window Chrome Moulding'],
	['296','Window Moulding'],
	['297','Windshield 1st Copy'],
	['298','Wireless Charger For LC300'],
	['299','Wooden Trim'],
	['300','Wooden Trim On Steering, And Gear Knob'],
	['301','Wooden Trim On Steering, Doors Side, Console'],
	['302','Xtreme LC300 (Xtreme Body Sticker)'],
	['303','Roof paint'],
	['304','2 doors (front and back) + 2 down mouldings paint'],
	['305','"Service kit 2 (15000 KM) Drain plug (for Oil pan drain), Gasket(for Oil pan drain plug), Oil filter, Air filter,AC Filter, FR Brake Pad Kit, RR Brake Pad Kit, V belt(for fan & Alternator), Glow plug Kit"']
            ];
        foreach ($addons as $key => $value):
        $addon[] = [
            'id'       => $value[0],
            'name' => $value[1]
        ];
        endforeach ;
        DB::table('addons')->insert($addon);
    }
}
