<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use DB;

class AddonTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    
            // ['1','Rear Camera']
    public function run(): void
    {
        $addons = [
    ['1','P','10.1 Inch - Android Rear Entertainment (All Brands/Models)'],
	['2','P','11.5 Inch - Android Rear Entertainment (All Brands/Models)'],
	['3','P','13.3 Inch - Android Rear Entertainment'],
	['4','P','13A Plug Volex'],
	['5','P','18 Size Legender Rims With Exchange 4 Pieces Only'],
	['6','P','2 Tone Paint'],
	['7','P','3 Core Wire 2.5mm Cable Roll'],
	['8','P','360 Camera'],
	['9','P','360 Camera 2D'],
	['10','P','360 Camera 3D'],
	['11','P','360 Camera HD'],
	['12','P','360 Camera Special LC300'],
	['13','P','360 Camera Universal Camera'],
	['14','P','3M Tinting (Sedan/Hatch Back)'],
	['15','P','3M Tinting (SUV)'],
	['16','P','4 Rims And 4 Tyres With Exchange Of Tyres'],
	['17','P','5 Rims And 5 Tyres From 17 To 18, Only Tyres Exchanged'],
	['18','P','5 Rims And 5 Tyres From 17 To 18, With Exchange Of Tyres And Rims'],
	['19','P','5 Rims And 5 Tyres From 17 To 19, Only Tyres Exchanged'],
	['20','P','5 Rims And 5 Tyres From 17 To 19, With Exchange Of Tyres And Rims'],
	['21','P','5 Rims And 5 Tyres From 18 To 20 Only Tyres Exchanged'],
	['22','P','5 Rims And 5 Tyres From 18 To 20 With Exchange Of Tyres And Rims'],
	['23','P','5 Rims And 5Tyres With Exchange Of Tyres 17 And 18 Size'],
	['24','P','70th Anniversary Badge'],
	['25','P','9" Inch - Android Rear Entertainment (All Brands/Models)'],
	['26','P','9" Inch - Featured Rear Entertainment (All Brands/Models)'],
	['27','P','AC Filter'],
	['28','P','Adventure Body Kit'],
	['29','P','Adventure Logo'],
	['30','P','Airport Vehicle Design Paint'],
	['31','P','Alloy Rims 4 Pieces'],
	['32','P','Alloy Rims 4 Pieces With Excahnge Of Alloy Rims'],
	['33','P','Alloy Rims 5 Pieces'],
	['34','P','Alloy Rims 5 Pieces 17 Size Without Alloy Rims Exchange'],
	['35','P','Alloy Rims 5 Pieces Without Exchange'],
	['36','P','Alloy Rims 5 Pieces Without Exchange 20 Inch'],
	['37','P','Ambience Dash Board Light + Doors'],
	['38','P','Ambulance With Sandwich Panel'],
	['39','P','Android DVD With Camera'],
	['40','P','Android Rear Entertainment (12 Inch)'],
	['41','P','Automatic Respirator For Ambulance'],
	['42','P','B6-Armoring'],
	['43','P','Back Light Chrome LED With Red Light'],
	['44','P','Bash Plate/ Skid Plate'],
	['45','P','Basic Ambulance'],
	['46','P','Basic Ambulance With Extended Fiber Glass Roof And Partition'],
	['47','P','Basic Ambulance With Wash Basin And 50-75 Litre Water Tank With Tap On The Underside'],
	['48','P',"Basic Ambulance'S Wash Basin Water Tank (50 Litres) And Posett"],
	['49','P','Basic Warranty For Gear And Engine'],
	['50','P','Basic Warranty For Gear And Engine (Without Claim)'],
	['51','P','Beacon Light'],
	['52','P','Bedliner'],
	['53','P','Belt Sticker Change'],
	['54','P','Black Edition Without Rims Paints'],
	['55','P','Blue Light Interior Down Side'],
	['56','P','Body Kit 2022 With Head Lights'],
	['57','P','Body Kit Fixing And Paint Charges Only'],
	['58','P','Body Kit Prado Fj150'],
	['59','P','Body Kit With Lexus Design 2022'],
	['60','P','Body Sticker'],
	['61','P','Body Sticker (All Brands/Models)'],
	['62','P','Bonnet Chrome Protector'],
	['63','P','Both Right Side Doors Painting'],
	['64','P','Brabus G800 Exterior Conversion With Rim And Tyre'],
	['65','P','Bsd Radar'],
	['66','P','Bullbar'],
	['67','P','Bullbar (Pickups & SUVs)'],
	['68','P','Bumper Complete (Both Fenders, Grill, Steel Bumper, Chrome Nickel, Bonnet Chrome, Inner Fender, Bumper Bracket)'],
	['69','P','Bumper Protector'],
	['70','P','Camping Edition'],
	['71','P','Canopy'],
	['72','P','Carry Body Canopy'],
	['73','P','Carryboy'],
	['74','P','Carryboy + Paint + Fixing'],
	['75','P','Ceramic Tinting'],
	['76','P','Ceramic Tinting (Sedan/Hatch Back)'],
	['77','P','Ceramic Tinting (SUV)'],
	['78','P','Chamois Fabric Seats'],
	['79','P','Chasis Sticker Change'],
	['80','P','Chrome Decoration'],
	['81','P','Chrome Door Handles'],
	['82','P','Chrome Front Grill'],
	['83','P','Chrome Window Moulding Cover (Original)'],
	['84','P','Complete Exhaust System'],
	['85','P','Customized Leather Napa Seats'],
	['86','P','Dashboard Paint'],
	['87','P','Digital Rear Camera'],
	['88','P','Digital Speedo Meter'],
	['89','P','Door Handle Chrome Cover'],
	['90','P','Door Sil 4 Sides'],
	['91','P','Door Sill Scuff Per Door (Not Like Original) Per Door'],
	['92','P','Down Spoilers Front And Back Modelilista (No Chrome Edition)'],
	['93','P','DVD With Camera'],
	['94','P','Electric Fuel Pump'],
	['95','P','Electric Seats (Each Seat)'],
	['96','P','Electric Seats Each Seat'],
	['97','P','Electric Suction Door Closer/Automatic Door Closer'],
	['98','P','Emergency Warning Triangle'],
	['99','P','Engine Air Filter'],
	['100','P','Exhaust Mounting With Fixing Charges'],
	['101','P','Exhaust Tip Inc Welding'],
	['102','P','Face Lift (Bumper, Grill, Fog Lamp, Fog Lamps Cover, Inner Fender,Bumper Brackets)'],
	['103','P','Fender Work'],
	['104','P','Fire Extinguisher 2Kg'],
	['105','P','First Aid Kit (42 Pieces)'],
	['106','P','Flag Pole (All Cars)'],
	['107','P','Flash Lights For Bumer'],
	['108','P','Floor Mat 3D'],
	['109','P','Floor Plastic'],
	['110','P','Fog Lamps'],
	['111','P','Fog Lamps Chrome Cover'],
	['112','P','Fog Lamps LED Light'],
	['113','P','Fog Lamps Yellow Light'],
	['114','P','Fog Lights (Pickups & SUVs)'],
	['115','P','Frame Guard'],
	['116','P','Front And Rear Bumper Chrome Edition With Paint And Fixing'],
	['117','P','Front Android DVD'],
	['118','P','Front Bumper Protector'],
	['119','P','Front DVD'],
	['120','P','Front DVD Android'],
	['121','P','Front DVD Big Screen (Android)'],
	['122','P','Front DVD Big Screen With Apple Car Play'],
	['123','P','Front DVD Normal Screen (Android)'],
	['124','P','Front DVD Original Screen'],
	['125','P','Front DVD Original Type'],
	['126','P','Front Glass Emblem'],
	['127','P','Front Grill'],
	['128','P','Front Lamps Black Out'],
	['129','P','Front LED Lights (Taiwan)'],
	['130','P','Front Original Double Volume DVD'],
	['131','P','Fuel Filter'],
	['132','P','Full Body Color Change To 4E9 + Coating'],
	['133','P','Full Body Peelable Paint'],
	['134','P','Gift Wrapping Bow'],
	['135','P','Grill Paint'],
	['136','P','Half Down Recovery Fabrication'],
	['137','P','Hidup Prado'],
	['138','P','High Quality Bullbar + Winch'],
	['139','P','Hilux Rims (Act0 5 Pieces'],
	['140','P','Hydraulic Jack (1500Kg)'],
	['141','P','Industrial Plug 16 Amp'],
	['142','P','Installation Of P338, P335, P334, P333, P332 With Extra Wires, Flexible Pipes And Brackets'],
	['143','P','Interior Change'],
	['144','P','Interior(Fibre Carbon)'],
	['145','P','Jbl Sound System'],
	['146','P','Jerry Can Carrier'],
	['147','P','Key Remote (China)'],
	['148','P','Land Cruiser Logo'],
	['149','P','LC300 Shadow Light'],
	['150','P','Leather Seats'],
	['151','P','Leather Seats (Mixed Leather)'],
	['152','P','Leather Seats (Napa+Leather) + Dash Board + Gear Console'],
	['153','P','Leather Seats Normal Holes Desgin'],
	['154','P','Leather Seats VXL Design'],
	['155','P','Leather Seats With LC200 Design'],
	['156','P','Leather Seats With LC300 Design'],
	['157','P','LED Board'],
	['158','P','LED Fog Lights'],
	['159','P','LED Front Grill'],
	['160','P','LED Front Lights'],
	['161','P','LED Lights'],
	['162','P','Legender Complete Kit'],
	['163','P','Legender Logo'],
	['164','P','Legender Rims 18 Size (4 Pieces)'],
	['165','P','Legender Word Imposing On Head Rest'],
	['166','P','Manual Respirator For Ambulance'],
	['167','P','Medical Portabel Suction Machine.'],
	['168','P','Micro Fiber Seats'],
	['169','P','Micro Fiber Seats With Normal Holes'],
	['170','P','Mix Leather Seat'],
	['171','P','Modellista Body Kit With Fenders'],
	['172','P','Monster Edition Conversion'],
	['173','P','Moulding Cover Front Right Side'],
	['174','P','Moulding Cover Rear Right Side'],
	['175','P','Mud Flap Set Of 4 Pieces'],
	['176','P','Multi-Flashing Roof Light Bar With Siren & Speaker'],
	['177','P','Napa Seats'],
	['178','P','Napa Seats With Center Leather Of Front 2 Seats'],
	['179','P','Night Package Lights'],
	['180','P','Normal Tinting (Pick Ups, Sc And Dc)'],
	['181','P','Normal Tinting (Sedan/Hatch Back)'],
	['182','P','Normal Tinting (SUV)'],
	['183','P','Off Road Package That Incliudes[ Bullbar, Off Road Tyres, Roof Rack, Bedliner, Winch, Spot Lights, Body Sticker, Rear Steel Bumper With 2 Tyres Bracket'],
	['184','P','Oil Filter'],
	['185','P','Oxygen Cylinder Regulator , Humidifier Flow Meter , Outlet For Ambulance'],
	['186','P','Parking Sensor'],
	['187','P','Pillar Exterior Plastic Moulding Front'],
	['188','P','Pillar Exterior Plastic Moulding Rear Back Side'],
	['189','P','Pillar Exterior Plastic Moulding Rear Front Side'],
	['190','P','Pirelli 295/40/22 Tyres And Rims'],
	['191','P','Plastic Cover Pic'],
	['192','P','Plastic Flooring (Sedan)'],
	['193','P','Plastic Flooring (SUV & Pickups)'],
	['194','P','Plastic Over Fender'],
	['195','P','Police Car Radio'],
	['196','P','Police Lights'],
	['197','P','Power Seats'],
	['198','P','Power Tail Gate'],
	['199','P','Prado Body Kit With Grill 2021 And Paint'],
	['200','P','Prado Interior Change'],
	['201','P','Prado Lexus Style Body Kit'],
	['202','P','Prado Lexus Style Grill'],
	['203','P','Prado Logo Door Light Down Reflection'],
	['204','P','Premium Leather Seats With Replica Of Bently Fly Spur Seats, Door Panels And Center Console'],
	['205','P','Push Start Original Type'],
	['206','P','Push Start Original Type( With Pressing Brake)'],
	['207','P','Push Start Original Type( Without Pressing Brake)'],
	['208','P','Push Start With Pressing Brake'],
	['209','P','Push Start With Pressing Brake ( Without Pressing Brake)'],
	['210','P','PVC Seats'],
	['211','P','Ramp Chrome'],
	['212','P','Rav 4 Adventure Conversion'],
	['213','P','Rear Badges'],
	['214','P','Rear Badges VXR Etc'],
	['215','P','Rear Camera'],
	['216','P','Rear Camera (All Sedans)'],
	['217','P','Rear Camera (SUV & Pickups)'],
	['218','P','Rear Chrome Bumper'],
	['219','P','Rear Chrome Nickel'],
	['220','P','Rear Chrome Nickel Fortuner'],
	['221','P','Rear Chrome Nickel Fortuner With Red Light'],
	['222','P','Rear Entertainment 11.5 Inch'],
	['223','P','Rear Entertainment LC300 Type'],
	['224','P','Rear Entertainment Original Type (Black)'],
	['225','P','Rear Mirror Camera'],
	['226','P','Rear Spoiler Light'],
	['227','P','Rear Spoiler With Light'],
	['228','P','Rear Steel Bumper'],
	['229','P','Rear Steel Bumper With Brackets'],
	['230','P','Rear Sub Bumper + Jerry Can + Spare Tyre Bracket'],
	['231','P','RHD Front Door'],
	['232','P','RHD Rear Door'],
	['233','P','Rims Paints'],
	['234','P','Roll Bar With Brake Light'],
	['235','P','Roll Bar With LED Lights'],
	['236','P','Rollbar'],
	['237','P','Rollbar (Metal)'],
	['238','P','Rollbar (Plastic)'],
	['239','P','Roof Rack'],
	['240','P','Roof Rack Lexus Style'],
	['241','P','Roof Rack Original Style'],
	['242','P','Roof Rail'],
	['243','P','Roof Wrapping (Black)'],
	['244','P','Sahara Badge'],
	['245','P','Seat Heater'],
	['246','P','Seat Heater Cooler'],
	['247','P','Seat Heating System'],
	['248','P','Shutter'],
	['249','P','Shutter Automatic'],
	['250','P','Shutter Manual'],
    ['251','P','Side Fender'],
	['252','P','Side Mirror Chrome Cover'],
	['253','P','Side Mirror Chrome Glass Assy'],
	['254','P','Side Mirror Right Side Cover'],
	['255','P','Side Mirror With Indicator Light'],
	['256','P','Side Moulding'],
	['257','P','Side Moulding With Plastic Cover'],
	['258','P','Side Step With Protection Iron Bar'],
	['259','P','Side Steps'],
	['260','P','Single Volume DVD'],
	['261','P','Sink With Cabinet For Ambulance'],
	['262','P','Snorkel'],
	['263','P','Spare Tire Carrier'],
	['264','P','Special Front DVD'],
	['265','P','Spot Lights (Pickups & SUVs)'],
	['266','P','Stainless Steel Waste Bin'],
	['267','P','Steering (Fibre Carbon And Alcantara)'],
	['268','P','Steering Buttons'],
	['269','P','Sticker Wrapping On Car Body'],
	['270','P','Stop Light Red'],
	['271','P','Storage Box'],
	['272','P','Sun Visor'],
	['273','P','Tail Door Handle Cover Hilux'],
	['274','P','Tail Gate Hydraulic'],
	['275','P','Tesla Screen'],
	['276','P','Tester'],
	['277','P','Tonneau Cover Hardtop Material'],
	['278','P','Tow Bar'],
	['279','P','Tow Bowl Bar'],
	['280','P','Tow Hitch Bar With Bracket'],
	['281','P','Tow Hitch Electric Socket 6 Pin (Pickups & SUVs)'],
	['282','P','Tw Twin Turbo'],
	['283','P','Twin Turbo Logo'],
	['284','P','Tyre 235/55R20'],
	['285','P','Tyre Down Work (With Exchange Of Old Gate)'],
	['286','P','Tyre Up Work (Without Exchange Of Old Gate)'],
	['287','P','Tyres 275/50/22 And Rims With Exchange'],
	['288','P','Tyres And Alloy Rims 5 Pieces 18 Inch With Exchange Of Wheels And Rims'],
	['289','P','Univesal Power Windows'],
	['290','P','Upgrade Front And Back Bumper To Full Option (Withpaint)'],
	['291','P','VIN Plate'],
	['292','P','Wheel Cover PVC'],
	['293','P','Wheel Spanner'],
	['294','P','Winch (Pickups & SUV)'],
	['295','P','Window Chrome Moulding'],
	['296','P','Window Moulding'],
	['297','P','Windshield 1st Copy'],
	['298','P','Wireless Charger For LC300'],
	['299','P','Wooden Trim'],
	['300','P','Wooden Trim On Steering, And Gear Knob'],
	['301','P','Wooden Trim On Steering, Doors Side, Console'],
	['302','P','Xtreme LC300 (Xtreme Body Sticker)'],
	['303','P','Roof paint'],
	['304','P','2 doors (front and back) + 2 down mouldings paint'],
	['305','P','"Service kit 2 (15000 KM) Drain plug (for Oil pan drain), Gasket(for Oil pan drain plug), Oil filter, Air filter,AC Filter, FR Brake Pad Kit, RR Brake Pad Kit, V belt(for fan & Alternator), Glow plug Kit"'],
    ['306','S',"Recovery Charges"],
	['307','S',"Roro Shipment"],
	['308','S',"20 FT  Cont."],
	['309','S',"40 FT Cont."],
	['310','S',"Land Transport"],
	['311','S',"Air Freight"],
	['312','S',"Destination Charges"],
	['313','D',"RTA Export Set Certificate"],
	['314','D',"Dubai Customs"],
	['315','D',"Certificates & Inspections"],
	['316','D',"Sea Freight Documentation"],
	['317','D',"RTA Local Registration"],
	['318','DP',"Agent"],
	['319','DP',"DP World"], 
	['320','D',"RTA PASSING FOR LOCAL REGISTRATION"],
	['321','D',"RTA LOCAL REGISTRATION CHARGES"],
	['322','D',"Marine Insurance"],
	['323','D',"Custom Duty"],
	['324','D',"DHL Charges"],
	['325','D',"Full Insurance"],
	['326','D',"RTA PASSING FOR LOCAL REGISTRATION"],
	['327','D','Milele Service Charges'],
	['328','D','Sales Order Cancellation Charges'],
	['329','D','Sale Document Set'],
	['330','D','Ownership Transfer']
];
        foreach ($addons as $key => $value):
        $addon[] = [
            'id'       => $value[0],
            'name' => $value[2],
			'addon_type' => $value[1]
        ];
        endforeach ;
        DB::table('addons')->insert($addon);
    }
}
